[versions]
adventure = "4.23.0"
bluecommands = "1.3.4"
bstats = "2.2.1"
configurate = "4.1.2"
junit = "5.8.2"
spongegradle = "2.2.0"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-ansi = { module = "net.kyori:adventure-text-serializer-ansi", version.ref = "adventure" }
aircompressor = { module = "io.airlift:aircompressor", version = "0.27" }
bluecommands-core = { module = "de.bluecolored:bluecommands-core", version.ref = "bluecommands" }
bluecommands-brigadier = { module = "de.bluecolored:bluecommands-brigadier", version.ref = "bluecommands" }
bluenbt = { module = "de.bluecolored:bluenbt", version = "3.5.0" }
brigadier = { module = "com.mojang:brigadier", version = "1.0.17" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
bstats-sponge = { module = "org.bstats:bstats-sponge", version.ref = "bstats" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version = "3.1.8" }
commons-cli = { module = "commons-cli:commons-cli", version = "1.5.0" }
commons-dbcp2 = { module = "org.apache.commons:commons-dbcp2", version = "2.9.0" }
configurate-hocon = { module = "org.spongepowered:configurate-hocon", version.ref = "configurate" }
configurate-gson = { module = "org.spongepowered:configurate-gson", version.ref = "configurate" }
fabric-permissions = { module = "me.lucko:fabric-permissions-api", version = "0.4.0" }
flow-math = { module = "com.flowpowered:flow-math", version = "1.0.3" }
gson = { module = "com.google.code.gson:gson", version = "2.8.9" }
guava = { module = "com.google.guava:guava", version = "33.3.0-jre" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "23.0.0" }
junit-core = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.32" }
lz4 = { module = "org.lz4:lz4-java", version = "1.8.0" }

[plugins]
cursegradle = { id = "com.matthewprenger.cursegradle", version = "1.4.0" }
forgegradle = { id = "net.minecraftforge.gradle", version = "[6.0.24,6.2)" }
hangar = { id = "io.papermc.hangar-publish-plugin", version = "0.1.2" }
loom = { id = "fabric-loom", version = "1.12-SNAPSHOT" }
minotaur = { id = "com.modrinth.minotaur", version = "2.8.7" }
node-gradle = { id = "com.github.node-gradle.node", version = "7.0.2" }
neoforge-gradle = { id = "net.neoforged.moddev", version = "2.0.107" }
shadow = { id = "com.gradleup.shadow", version = "9.1.0" }
sponge-plugin = { id = "org.spongepowered.gradle.plugin", version.ref = "spongegradle" }
sponge-ore = { id = "org.spongepowered.gradle.ore", version.ref = "spongegradle" }
spotless = { id = "com.diffplug.spotless", version = "6.25.0" }